In [14]:
import torch
t1 = torch.zeros(2,3)
t1.shape
t2 = torch.ones(3,4,5)
t1[0,2] = 7
t1

tensor([[0., 0., 7.],
        [0., 0., 0.]])

In [40]:
t3 = torch.tensor([[1.5,2.4], [3.1,4], [5.6,6.9]])
int(t3[1,0])

3

In [49]:
t4 = torch.tensor([1,2,3,4,5,6,7])
t4[1:-1:3]

tensor([2, 5])

In [51]:
t3[0:-1:2,0]

tensor([1.5000])

In [64]:
t3[None][None].shape

torch.Size([1, 1, 3, 2])

In [77]:
img = torch.randn(3,4,4)
gray_scale_img = img.mean(-3)
gray_scale_img.shape

torch.Size([4, 4])

In [80]:
batch = torch.randn(5,3,4,4)
gray_scale_batch = batch.mean(-3)
gray_scale_batch.shape

torch.Size([5, 4, 4])

In [81]:
weights = torch.tensor([.21, .71, .08])

In [83]:
t4 * 8

tensor([ 8, 16, 24, 32, 40, 48, 56])

In [85]:
t5 = torch.rand(2,3)
t6 = torch.rand(2,3)
t5, t6, t5 * t6

(tensor([[0.4409, 0.6255, 0.4340],
         [0.3587, 0.7110, 0.9393]]),
 tensor([[0.8516, 0.2211, 0.7540],
         [0.2952, 0.9016, 0.0515]]),
 tensor([[0.3755, 0.1383, 0.3273],
         [0.1059, 0.6410, 0.0483]]))

In [102]:
#torch.unsqueeze(weights, -1)
weights_unsq = weights.unsqueeze(-1).unsqueeze(-1)

gray_scale_img_weighted = (img * weights_unsq).sum(-3)
gray_scale_batch_weighted = (batch * weights_unsq).sum(-3)

torch.Size([5, 4, 4])

In [124]:
weights_named = torch.tensor([.21, .71, .08], names=['channels'])
img_named = img.refine_names(..., 'channels', 'height', 'width')
img_named.names

weights_aligned = weights_named.align_as(img_named)
weights_aligned.names

gray_scale_img_named = (img_named * weights_aligned).sum('channels')
gray_scale_img_named.rename(None)

tensor([[ 0.3503,  0.3136, -0.3230,  0.2390],
        [-0.4159, -0.6395,  0.0583, -1.1497],
        [ 0.7602,  1.0278, -0.7294,  0.4760],
        [ 0.8397,  0.0578,  0.6677,  0.3167]])

In [156]:
t4 = torch.tensor([1,2,3,4,5,6,7], dtype=torch.int32)
t5 = t4.to(torch.int16)
((t5 * t4) > 6).dtype

torch.bool

In [167]:
pts = torch.tensor([[1,2],[3,4],[5,6]])
pts.shape
pts_storage = pts.storage()
pts_storage[4] = 7
pts #updated!


tensor([[1, 2],
        [3, 4],
        [7, 6]])

In [174]:
pts[2].storage_offset()

4

pts.stride() # in order to access element at index [i,j] within pts, offset = 2 * i + 1 * j

In [177]:
pts.stride()

(2, 1)

In [188]:
t6 = torch.tensor([[1,2,3,4],[5,6,7,8]])
t6, t6.stride(), t6[1][2], t6.storage()
t7 = torch.randn(2,3,4)
t7, t7.storage(), t7.stride(), 
# [i,j,k]: offset = 12 * i + 4 * j + 1 * k

(tensor([[[-1.0134,  0.0480, -0.1056, -0.9801],
          [ 0.5300,  1.1202, -0.3877, -0.2299],
          [ 0.1239,  0.8531, -0.4578, -0.4898]],
 
         [[ 0.7530, -1.9590, -0.7500,  0.1455],
          [-0.9091, -0.0852,  1.7728, -0.3216],
          [-2.4149, -0.2259, -0.3639,  2.0277]]]),
  -1.0133577585220337
  0.047989506274461746
  -0.10557320713996887
  -0.9800690412521362
  0.5300299525260925
  1.1201993227005005
  -0.38772791624069214
  -0.22993898391723633
  0.12391053885221481
  0.8530968427658081
  -0.4577876329421997
  -0.48982948064804077
  0.7529871463775635
  -1.9589706659317017
  -0.7499852180480957
  0.14550261199474335
  -0.9090502262115479
  -0.08520094305276871
  1.7728304862976074
  -0.32162848114967346
  -2.4149115085601807
  -0.22588740289211273
  -0.36390283703804016
  2.0276613235473633
 [torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 24],
 (12, 4, 1))

In [191]:
t7[1,1,2] # offset = 12 * 1 + 4 * 1 + 1 * 2 = 18

tensor(1.7728)

In [197]:
t5.zero_()
t5

tensor([0, 0, 0, 0, 0, 0, 0], dtype=torch.int16)

In [213]:
t8 = t6[1].clone()
t8[1] = 10
t6.storage_offset()

0

In [232]:
t9 = t6.t()
t6.shape, t9.shape, t6.stride(), t9.stride()

(torch.Size([2, 4]), torch.Size([4, 2]), (4, 1), (1, 4))

In [240]:
t10 = torch.randn(2,3,4)
t11 = t10.transpose(0,2)
t10.shape, t10.stride(), t11.shape, t11.stride(), id(t11.storage()), id(t10.storage())

(torch.Size([2, 3, 4]),
 (12, 4, 1),
 torch.Size([4, 3, 2]),
 (1, 4, 12),
 4690309024,
 4690309024)

In [248]:
#t12 = torch.tensor([1,2], device='cuda')
t12 = torch.tensor([1,2])
#t12.to(device='cuda')

In [255]:
arr = t6.numpy()


In [258]:
import numpy as np
arr = np.array([1,2,3])
t13 = torch.from_numpy(arr)
t13.shape

torch.Size([3])

In [260]:
torch.save(t13, './t13.t')

In [262]:
t14 = torch.load('./t13.t')
t14

tensor([1, 2, 3])